apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-deployer
  namespace: cicd

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tekton-deployer-role
  namespace: cicd

rules:

  # Deployments
  - apiGroups:
      - apps
    resources:
      - deployments
      - deployments/status
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  # Services
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  # Pods
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch

  # HPA
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  name: tekton-deployer-binding
  namespace: cicd

subjects:

  - kind: ServiceAccount
    name: tekton-deployer
    namespace: cicd

roleRef:

  kind: Role
  name: tekton-deployer-role
  apiGroup: rbac.authorization.k8s.io