# ==========================================
# STAGE 1 - BUILD VUE
# ==========================================

FROM node:22-alpine AS frontend-builder

WORKDIR /app/ui

COPY ui/package*.json ./

RUN npm install axios
RUN npm install

COPY ui/ .

RUN npm run build


# ==========================================
# STAGE 2 - BUILD GOLANG
# ==========================================

FROM golang:1.27-alpine AS backend-builder

WORKDIR /app

# Download dependency
COPY go.mod go.sum ./

RUN go mod download

# Copy source code
COPY main.go .

# Build aplikasi
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -o server main.go


# ==========================================
# STAGE 3 - FINAL IMAGE
# ==========================================

FROM alpine:3.22

WORKDIR /app

# Install CA certificates
RUN apk --no-cache add ca-certificates

# Copy binary Go
COPY --from=backend-builder /app/server .

# Copy hasil build Vue
COPY --from=frontend-builder /app/ui/dist ./ui/dist

# Copy database CSV
COPY data ./data

# Port aplikasi
EXPOSE 8888

# Jalankan aplikasi
CMD ["./server"]