services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile-go
    container_name: employee-backend
    ports:
      - "8888:8888"
    volumes:
      - ./data:/app/data
    restart: unless-stopped

  frontend:
    build:
      context: ./ui
      dockerfile: Dockerfile-vue
    container_name: employee-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./ui:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped