apiVersion: tekton.dev/v1
kind: PipelineRun

metadata:
  generateName: employee-ci-cd-

spec:

  pipelineRef:
    name: employee-ci-cd

  taskRunTemplate:
    serviceAccountName: tekton-deployer

  params:

    - name: repo-url
      value: https://github.com/aripribadi010187-droid/go-project.git

    - name: revision
      value: main

    - name: backend-image
      value: aripribadi010187/go-project_backend

    - name: frontend-image
      value: aripribadi010187/go-project_frontend

    - name: image-tag
      value: v1

  workspaces:

    - name: shared-workspace

      volumeClaimTemplate:

        spec:

          accessModes:
            - ReadWriteOnce

          resources:

            requests:
              storage: 5Gi