apiVersion: tekton.dev/v1
kind: Pipeline

metadata:
  name: employee-ci-cd
  namespace: cicd

spec:

  params:

    - name: repo-url
      type: string

    - name: revision
      type: string
      default: main

    - name: backend-image
      type: string
      default: aripribadi010187/go-project_backend

    - name: frontend-image
      type: string
      default: aripribadi010187/go-project_frontend

    - name: image-tag
      type: string

  workspaces:

    - name: shared-workspace

  tasks:

    # =====================================
    # 1. CLONE
    # =====================================

    - name: clone

      taskRef:
        name: git-clone

      params:

        - name: url
          value: $(params.repo-url)

        - name: revision
          value: $(params.revision)

        - name: deleteExisting
          value: "true"

      workspaces:

        - name: output
          workspace: shared-workspace


    # =====================================
    # 2. BACKEND TEST
    # =====================================

    - name: backend-test

      runAfter:
        - clone

      taskRef:
        name: backend-test

      workspaces:

        - name: source
          workspace: shared-workspace



    # =====================================
    # 3. BACKEND BUILD
    # =====================================

    - name: backend-build

      runAfter:
        - backend-test

      taskRef:
        name: backend-build-push

      params:

        - name: IMAGE
          value: $(params.backend-image)

        - name: TAG
          value: $(params.image-tag)

      workspaces:

        - name: source
          workspace: shared-workspace


    # =====================================
    # 4. FRONTEND BUILD
    # =====================================

    - name: frontend-build

      runAfter:
        - backend-build

      taskRef:
        name: frontend-build-push

      params:

        - name: IMAGE
          value: $(params.frontend-image)

        - name: TAG
          value: $(params.image-tag)

      workspaces:

        - name: source
          workspace: shared-workspace


    # =====================================
    # 5. DEPLOY
    # =====================================

    - name: deploy

      runAfter:
        - backend-build
        - frontend-build

      taskRef:
        name: deploy-minikube

      params:

        - name: BACKEND_IMAGE
          value: $(params.backend-image)

        - name: FRONTEND_IMAGE
          value: $(params.frontend-image)

        - name: TAG
          value: $(params.image-tag)

      workspaces:

        - name: source
          workspace: shared-workspace