apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-backend
  template:
    metadata:
      labels:
        app: employee-backend
    spec:
      containers:
        - name: backend
          image: aripribadi010187/go-project_backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"

          volumeMounts:
            - name: employee-data
              mountPath: /app/data
      volumes:
        - name: employee-data
          configMap:
            name: employee-data